version: '3.4'

services:
  events:
    image: events
    ports:
    - "8080:80"
    build:
      context: .
      dockerfile: Events/Dockerfile
    environment:
    - REDIS=redis
    - ENVENTSTORE_URI=tcp://admin:changeit@eventstore:1113
  redis:
    image: redis:alpine
  eventstore:
    image: eventstore/eventstore:release-4.1.1-hotfix1
    ports:
    - "2113:2113"
    - "1113:1113"
